run nox in CI

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -11,14 +11,18 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - uses: ./.github/actions/setup-depiction
+      - name: Set up Python
+        uses: actions/setup-python@v5
         with:
           python-version: 3.12
+      - name: Install nox
+        shell: bash
+        run: pip install nox[uv]
       - name: Run unit tests
-        run: cd tests && python -m unittest discover -s ./unit -p 'test_*.py'
-      - name: Code style
-        run: ruff check || true
-        if: success() || failure()
+        run: nox -s tests
+#      - name: Code style
+#        run: ruff check || true
+#        if: success() || failure()
 #code_style:
 #  name: Code Style
 #  runs-on: ubuntu-latest
